//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_ExamPart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ES_ExamPart()
        {
            this.ES_User_ExamPart = new HashSet<ES_User_ExamPart>();
            this.ES_ExamLog = new HashSet<ES_ExamLog>();
        }
    
        public int EmPtId { get; set; }
        public System.DateTime EmPtStart { get; set; }
        public System.DateTime EmPtEnd { get; set; }
        public bool IsDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ES_User_ExamPart> ES_User_ExamPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ES_ExamLog> ES_ExamLog { get; set; }
    }
}
