//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_FillAnswer
    {
        public int FAId { get; set; }
        public int FQId { get; set; }
        public string FAContent { get; set; }
        public int FAScore { get; set; }
    
        public virtual ES_FillQuestion ES_FillQuestion { get; set; }
    }
}
