//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_SelectQuestion
    {
        public int SQId { get; set; }
        public string SQTitle { get; set; }
        public string SQTrueAns { get; set; }
        public string SQAns1 { get; set; }
        public string SQAns2 { get; set; }
        public string SQAns3 { get; set; }
        public string SQAns4 { get; set; }
        public int SQScore { get; set; }
    }
}
