//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_User_ExamPaper
    {
        public int UEmPaper { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EmPaperId { get; set; }
        public bool IsDel { get; set; }
    
        public virtual ES_ExamPaper ES_ExamPaper { get; set; }
        public virtual ES_User ES_User { get; set; }
    }
}
